namespace RemoteServer.Configuration;

/// <summary>Server configuration. Secrets and keys come from files/secrets, not from the repo.</summary>
public sealed class ServerOptions
{
    public const string SectionName = "Server";

    /// <summary>
    /// Path to the ECDSA P-256 private command-signing key (PEM). Agents pin the public
    /// counterpart (CommandSigningPublicKey). This must never be committed.
    /// </summary>
    public string CommandSigningKeyPath { get; set; } = string.Empty;

    /// <summary>Path to the CA certificate (PEM) used to sign client certs. Generated by the server if missing.</summary>
    public string CaCertPath { get; set; } = "/etc/remoteserver/ca.crt";

    /// <summary>Path to the CA private key (PEM), readable only by the service user.</summary>
    public string CaKeyPath { get; set; } = "/etc/remoteserver/ca.key";

    /// <summary>Validity of issued client certificates in days.</summary>
    public int ClientCertValidityDays { get; set; } = 825;

    /// <summary>Path to the 32-byte key used for encrypting DB secrets such as vnc_secret at rest.</summary>
    public string SecretKeyPath { get; set; } = "/etc/remoteserver/secret.key";

    /// <summary>Storage directory for update packages. Survives redeploys and backs /api/updates.</summary>
    public string PackagesDir { get; set; } = "/var/lib/remoteserver/packages";

    /// <summary>Staging/trigger/result directory for server self-update. remotesrv-writable; the
    /// privileged systemd helper (deploy.sh) reads the staged tar.gz/upgrade.sql and writes result.*.</summary>
    public string UpdatesDir { get; set; } = "/var/lib/remoteserver/updates";

    /// <summary>Trigger/result directory for the console-driven fleet-identity backup. remotesrv-writable;
    /// the privileged helper (console-backup.sh) reads the passphrase trigger and writes backup.enc plus
    /// backup.status/at/log/name. The server never reads the fleet's keys itself - it cannot: the bastion
    /// SSH host key that agents pin is root-owned.</summary>
    public string ConsoleBackupDir { get; set; } = "/var/lib/remoteserver/console-backup";

    /// <summary>Directory for the server's own daily-rolling log files, served by /admin/server/logs. Must be
    /// writable by the service user (setup.sh gives it /var/lib/remoteserver); when it cannot be created the
    /// server keeps the newest records in memory only and says so in the diagnostics snapshot. On Windows
    /// (development) an unreachable Linux default falls back to a "logs" folder next to the binary.</summary>
    public string LogDir { get; set; } = "/var/lib/remoteserver/logs";

    /// <summary>Where the first admin's temporary password is written when the database is seeded (owner-only
    /// file, 0600). It used to go to the server log, which is kept, shipped and readable more widely than
    /// a one-time secret should be. The file is removed once that password has been changed.</summary>
    public string FirstAdminPasswordPath { get; set; } = "/var/lib/remoteserver/first-admin-password.txt";

    /// <summary>How many days of log files to keep.</summary>
    public int LogRetentionDays { get; set; } = 14;

    /// <summary>How many days of audit rows to keep: operator actions with their source addresses, which is
    /// personal data with no reason to live forever. 0 keeps everything.</summary>
    public int AuditRetentionDays { get; set; } = 365;

    /// <summary>The health alerts (see <see cref="Services.HealthAlertWatcher"/>): e-mail to the support address when a
    /// check starts failing, and once more when it clears.</summary>
    public AlertOptions Alerts { get; set; } = new();

    /// <summary>
    /// A secret nginx sends in <c>X-RAC-Proxy</c> on every request it forwards. Kestrel's port is reachable not
    /// only from nginx but through the bastion's loopback forwards too, so the identity headers nginx derives from
    /// the client certificate (<c>X-Client-Verify</c>, <c>X-Client-Dn</c>) and the real client address
    /// (<c>X-Real-IP</c>, <c>X-Forwarded-For</c>) are believed only on requests that carry it. Empty: they are
    /// believed from any caller, as before - set it only once nginx sends it, or every agent is turned away.
    /// </summary>
    public string ProxySecret { get; set; } = string.Empty;

    /// <summary>Public server base URL, for example https://c2.example.com, embedded in bootstrap blobs.</summary>
    public string PublicUrl { get; set; } = string.Empty;

    /// <summary>
    /// ProductCode of every MSI this server generates. Fixed on purpose: deployment tools (Intune, GPO, SCCM)
    /// detect an installation by its ProductCode, and a freshly generated code made every rebuilt MSI look
    /// like a different product - so it was pushed onto machines that already ran the agent, where the shared
    /// UpgradeCode turned it into a major upgrade that uninstalls and re-enrolls the device. The MSI is only
    /// the first installer; versions ship through the release channels, so the ProductCode has no reason to
    /// move. The PackageCode still changes with every build. Override only if you must keep a code that is
    /// already deployed in your estate.
    /// </summary>
    public string MsiProductCode { get; set; } = "2056042B-3070-4A61-BCA3-F7CDF988722A";

    /// <summary>
    /// Oldest console client version allowed to sign in. Older clients receive "mustUpdate"
    /// without a session and must update. Empty = no limit.
    /// </summary>
    public string MinClientVersion { get; set; } = "1.5.0.0";

    /// <summary>MSI Authenticode signing. Optional: empty CertPath means unsigned/test use.</summary>
    public MsiSigningOptions MsiSigning { get; set; } = new();

    /// <summary>Bastion (reverse SSH tunnel) access data included in enrollment responses.</summary>
    public BastionOptions Bastion { get; set; } = new();
}

/// <summary>
/// MSI Authenticode signing with osslsigncode on Linux. Empty CertPath means skipped
/// (unsigned MSI; SmartScreen warns, but Intune push/silent install is unaffected).
/// </summary>
public sealed class AlertOptions
{
    public bool Enabled { get; set; } = true;
    /// <summary>Minutes between two checks (5 .. 1440).</summary>
    public int IntervalMinutes { get; set; } = 30;
    /// <summary>Hours before a check that keeps failing is mailed again.</summary>
    public int RepeatHours { get; set; } = 24;
    /// <summary>A disk with less free space than this (percent, or under 1 GB) is an alert.</summary>
    public int DiskFreePercent { get; set; } = 10;
    /// <summary>A database round trip slower than this is an alert.</summary>
    public int DbLatencyWarnMs { get; set; } = 2000;
    /// <summary>Days left on the public TLS certificate below which it is an alert (certbot renews at 30).</summary>
    public int TlsDaysWarn { get; set; } = 14;
    /// <summary>Days ahead of a device certificate's end at which the device is named.</summary>
    public int DeviceCertDaysWarn { get; set; } = 60;
}

public sealed class MsiSigningOptions
{
    /// <summary>Path to the code-signing certificate (PFX). Empty = no signing.</summary>
    public string CertPath { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string TimestampUrl { get; set; } = "http://timestamp.digicert.com";
}

/// <summary>Bastion config. Host/HostKey are machine-specific and come from env/appsettings on the box, not the repo.</summary>
public sealed class BastionOptions
{
    /// <summary>Public bastion host where agents establish ssh -R, usually the server domain.</summary>
    public string Host { get; set; } = string.Empty;

    public int Port { get; set; } = 22;

    public string User { get; set; } = "agent";

    /// <summary>Bastion host key for pinning ("type base64", without comment).</summary>
    public string HostKey { get; set; } = string.Empty;

    /// <summary>Path to the SSH CA private key used by ssh-keygen -s. Readable only by remotesrv.</summary>
    public string SshCaKeyPath { get; set; } = "/etc/remoteserver/agent_ca";

    /// <summary>
    /// The OpenSSH revocation list (KRL) of deleted devices' SSH keys, for the bastion's <c>RevokedKeys</c>. The
    /// server keeps it up to date (and its source list next to it, same name with .txt); empty disables it.
    /// </summary>
    public string RevokedKeysPath { get; set; } = "/var/lib/remoteserver/ssh/revoked_keys.krl";

    /// <summary>Validity of issued SSH certificates in days.</summary>
    public int SshCertValidityDays { get; set; } = 825;

    /// <summary>Validity (hours) of short-lived operator SSH certificates minted on login for the keyless
    /// Linux operator console. Matches the session lifetime so the cert and session expire together.</summary>
    public int OperatorCertValidityHours { get; set; } = 8;

    /// <summary>Range for stable per-device tunnel ports (inclusive min, exclusive max).</summary>
    public int TunnelPortMin { get; set; } = 50000;
    public int TunnelPortMax { get; set; } = 60000;
}
