namespace RemoteServer.Configuration;

/// <summary>Server configuration. Secrets and keys come from files/secrets, not from the repo.</summary>
public sealed class ServerOptions
{
    public const string SectionName = "Server";

    /// <summary>
    /// Path to the ECDSA P-256 private command-signing key (PEM). Agents pin the public
    /// counterpart (CommandSigningPublicKey). This must never be committed.
    /// </summary>
    public string CommandSigningKeyPath { get; set; } = string.Empty;

    /// <summary>Path to the CA certificate (PEM) used to sign client certs. Generated by the server if missing.</summary>
    public string CaCertPath { get; set; } = "/etc/remoteserver/ca.crt";

    /// <summary>Path to the CA private key (PEM), readable only by the service user.</summary>
    public string CaKeyPath { get; set; } = "/etc/remoteserver/ca.key";

    /// <summary>Validity of issued client certificates in days.</summary>
    public int ClientCertValidityDays { get; set; } = 825;

    /// <summary>Path to the 32-byte key used for encrypting DB secrets such as vnc_secret at rest.</summary>
    public string SecretKeyPath { get; set; } = "/etc/remoteserver/secret.key";

    /// <summary>Storage directory for update packages. Survives redeploys and backs /api/updates.</summary>
    public string PackagesDir { get; set; } = "/var/lib/remoteserver/packages";

    /// <summary>Staging/trigger/result directory for server self-update. remotesrv-writable; the
    /// privileged systemd helper (deploy.sh) reads the staged tar.gz/upgrade.sql and writes result.*.</summary>
    public string UpdatesDir { get; set; } = "/var/lib/remoteserver/updates";

    /// <summary>Public server base URL, for example https://c2.example.com, embedded in bootstrap blobs.</summary>
    public string PublicUrl { get; set; } = string.Empty;

    /// <summary>
    /// Oldest console client version allowed to sign in. Older clients receive "mustUpdate"
    /// without a session and must update. Empty = no limit.
    /// </summary>
    public string MinClientVersion { get; set; } = "1.5.0.0";

    /// <summary>MSI Authenticode signing. Optional: empty CertPath means unsigned/test use.</summary>
    public MsiSigningOptions MsiSigning { get; set; } = new();

    /// <summary>Bastion (reverse SSH tunnel) access data included in enrollment responses.</summary>
    public BastionOptions Bastion { get; set; } = new();
}

/// <summary>
/// MSI Authenticode signing with osslsigncode on Linux. Empty CertPath means skipped
/// (unsigned MSI; SmartScreen warns, but Intune push/silent install is unaffected).
/// </summary>
public sealed class MsiSigningOptions
{
    /// <summary>Path to the code-signing certificate (PFX). Empty = no signing.</summary>
    public string CertPath { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string TimestampUrl { get; set; } = "http://timestamp.digicert.com";
}

/// <summary>Bastion config. Host/HostKey are machine-specific and come from env/appsettings on the box, not the repo.</summary>
public sealed class BastionOptions
{
    /// <summary>Public bastion host where agents establish ssh -R, usually the server domain.</summary>
    public string Host { get; set; } = string.Empty;

    public int Port { get; set; } = 22;

    public string User { get; set; } = "agent";

    /// <summary>Bastion host key for pinning ("type base64", without comment).</summary>
    public string HostKey { get; set; } = string.Empty;

    /// <summary>Path to the SSH CA private key used by ssh-keygen -s. Readable only by remotesrv.</summary>
    public string SshCaKeyPath { get; set; } = "/etc/remoteserver/agent_ca";

    /// <summary>Validity of issued SSH certificates in days.</summary>
    public int SshCertValidityDays { get; set; } = 825;

    /// <summary>Range for stable per-device tunnel ports (inclusive min, exclusive max).</summary>
    public int TunnelPortMin { get; set; } = 50000;
    public int TunnelPortMax { get; set; } = 60000;
}
