// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteServer.Data;

#nullable disable

namespace RemoteServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614191021_Reset_1_5_0")]
    partial class Reset_1_5_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RemoteServer.Data.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TargetDeviceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nonce")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("json");

                    b.Property<string>("ResultJson")
                        .HasColumnType("json");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Status");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AgentRestarts")
                        .HasColumnType("int");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("BootTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CertThumbprint")
                        .HasColumnType("longtext");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("longtext");

                    b.Property<bool?>("ConsentRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HelperVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("LastIncident")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoggedInUser")
                        .HasColumnType("longtext");

                    b.Property<int>("LoginFailCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LoginLockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("OsVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicIpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("SshPublicKey")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TunnelPort")
                        .HasColumnType("int");

                    b.Property<bool?>("UnattendedAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UpdateAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VncLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VncSecret")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("VncSecretUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VncVersion")
                        .HasColumnType("longtext");

                    b.Property<bool>("VpnActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WifiSsid")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("Status");

                    b.HasIndex("TunnelPort")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("ConsentRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<bool>("UnattendedAllowed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("DeviceGroups");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.DeviceTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CollectedAt");

                    b.ToTable("DeviceTelemetry");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.EnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<string>("MsiFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UsedByDeviceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("EnrollmentTokens");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.HelloCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HelloCredentials");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.ReleasePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Channel", "Component", "UploadedAt");

                    b.ToTable("ReleasePackages");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.RemoteSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConsentState")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RemotePort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "OpenedAt");

                    b.ToTable("RemoteSessions");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.ServerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EmailProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GraphClientId")
                        .HasColumnType("longtext");

                    b.Property<string>("GraphClientSecretEnc")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("GraphSecretExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GraphSender")
                        .HasColumnType("longtext");

                    b.Property<string>("GraphTenantId")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("SecretExpiryNotifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SmtpFrom")
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpPasswordEnc")
                        .HasColumnType("longtext");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<bool>("SmtpUseTls")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("longtext");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ResetCodeExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResetCodeHash")
                        .HasColumnType("longtext");

                    b.Property<bool>("TotpConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGrants");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.Device", b =>
                {
                    b.HasOne("RemoteServer.Data.Entities.DeviceGroup", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.HelloCredential", b =>
                {
                    b.HasOne("RemoteServer.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserGrant", b =>
                {
                    b.HasOne("RemoteServer.Data.Entities.User", "User")
                        .WithMany("Grants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserRole", b =>
                {
                    b.HasOne("RemoteServer.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemoteServer.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.UserSession", b =>
                {
                    b.HasOne("RemoteServer.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.DeviceGroup", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RemoteServer.Data.Entities.User", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
