using System.Collections.Generic;

namespace RemoteServer.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> En = new()
    {
        [nameof(CertificateAuthority_CAFilesAreMissing)] = "CA files are missing ('{0}', '{1}'). ",
        [nameof(CertificateAuthority_GenerateThemDuringProvisioningDeploy)] = "Generate them during server setup (deploy/setup.sh); the server only reads them.",
        [nameof(CertificateAuthority_CALoadedSubject)] = "CA loaded: {Subject}",
        [nameof(CommandService_UnknownDeviceCommandDiscardedDevice)] = "Unknown device, command discarded: {Device}",
        [nameof(CommandService_CommandDeliveredToDeviceType)] = "Command delivered to {Device}: {Type}",
        [nameof(CommandService_DeviceOfflineCommandRemainsQueued)] = "Device offline, command remains queued {Device}: {Type}",
        [nameof(CommandSigner_CommandSigningPrivateKeyNot)] = "Command signing private key not found: '{0}'. Set Server:CommandSigningKeyPath.",
        [nameof(EmailSender_MissingRecipient)] = "Missing recipient.",
        [nameof(EmailSender_NoEmailSettings)] = "No email settings.",
        [nameof(EmailSender_NoActiveEmailProviderConfigured)] = "No active email provider configured.",
        [nameof(EmailSender_EMailDeliveryErrorProvider)] = "E-mail delivery error ({Provider}).",
        [nameof(EmailSender_MissingSMTPHost)] = "Missing SMTP host.",
        [nameof(EmailSender_MissingSenderSmtpFromSmtpUser)] = "Missing sender (SmtpFrom/SmtpUser).",
        [nameof(EmailSender_MissingGraphSettingsTenantClient)] = "Missing Graph settings (tenant/client/sender).",
        [nameof(EmailSender_MissingGraphClientSecret)] = "Missing Graph client secret.",
        [nameof(EmailSender_TokenResponseDoesNotContain)] = "Token response does not contain access_token.",
        [nameof(EmailSender_TokenError)] = "Token error ({0}): {1}",
        [nameof(EmailSender_SendMailError)] = "sendMail error ({0}): {1}",
        [nameof(EnrollmentService_CSRSigningFailedDeviceDevice)] = "CSR signing failed (device {Device}).",
        [nameof(EnrollmentService_DeviceEnrolledDeviceHost)] = "Device enrolled: {Device} ({Host})",
        [nameof(MsiBuilder_MSIBuiltFileSizeBytes)] = "MSI built: {File} ({Size} bytes)",
        [nameof(MsiBuilder_MSIBuildError)] = "MSI build error.",
        [nameof(MsiBuilder_MSISigned)] = "MSI signed.",
        [nameof(MsiBuilder_MSISigningSkippedFailedOsslsigncode)] = "MSI signing skipped/failed (osslsigncode rc={Code}): {Output}",
        [nameof(MsiBuilder_MSISigningErrorSkipped)] = "MSI signing error (skipped).",
        [nameof(MsiBuilder_WixlErrorRcCodeOutput)] = "wixl error (rc={Code}): {Output}",
        [nameof(Program_UnknownUser)] = "unknown user",
        [nameof(Program_InvalidPassword)] = "invalid password",
        [nameof(Program_InvalidTOTP)] = "invalid TOTP",
        [nameof(Program_UnknownDevice)] = "unknown device",
        [nameof(Program_InvalidOrExpiredToken)] = "invalid or expired token",
        [nameof(Program_AgentConnectedDevice)] = "Agent connected: {Device}",
        [nameof(Program_WSClosedDevice)] = "WS closed: {Device}",
        [nameof(Program_AgentDisconnectedDevice)] = "Agent disconnected: {Device}",
        [nameof(Program_Devices)] = "{0} · {1} · {2} -> {3} devices",
        [nameof(Program_SetServerPublicUrlOrProvide)] = "set Server:PublicUrl or provide ?serverUrl=",
        [nameof(Program_SmtpPasswordChanged)] = "; smtpPassword=changed",
        [nameof(Program_GraphSecretChanged)] = "; graphSecret=changed",
        [nameof(Program_ThisIsATestEmail)] = "This is a test email from RemoteAppClient server settings. If you received it, email delivery works.",
        [nameof(Program_BOOTSTRAPAdminCreatedUsernameAdmin)] = "BOOTSTRAP admin created - username: admin, TEMPORARY password: {Temp} (must be changed at first sign-in)",
        [nameof(Program_RekeyCsrFailed)] = "Re-key: the CSR of device {Device} could not be signed",
        [nameof(Program_RekeyIssued)] = "Re-key: new certificate issued to device {Device} ({Reason}, key in {Provider}); awaiting its confirmation",
        [nameof(Program_RekeyConfirmed)] = "Re-key: device {Device} confirmed its new certificate; the old one retires in a few minutes",
        [nameof(Program_BOOTSTRAPAdminCreatedPasswordFile)] = "BOOTSTRAP admin created - username: admin, the TEMPORARY password is in {Path} (must be changed at first sign-in)",
        [nameof(FirstAdminHandover_CouldNotWrite)] = "Could not write the first admin password file {Path}",
        [nameof(FirstAdminHandover_CouldNotRemove)] = "Could not remove the first admin password file {Path}",
        [nameof(Program_AuditWriteErrorAction)] = "Audit write error: {Action}",
        [nameof(Program_FailedAttemptsLast)] = "{0} failed attempts (last: {1})",
        [nameof(Program_ThereWereFailedSignIn)] = "There were {1} failed sign-in/password attempts from device \"{0}\\",
        [nameof(Program_LastAttemptedUsernameSourceIP)] = "Last attempted username: {0}\nSource IP: {1}\nTime: {2:yyyy-MM-dd HH:mm} UTC\n\n",
        [nameof(Program_UnlockInTheClientGo)] = "Unlock: in the client, go to Devices -> the device -> \"Unlock sign-in\" (admin only).",
        [nameof(Program_RemoteAppClientDeviceSignInLocked)] = "RemoteAppClient - device sign-in locked (failed attempts)",
        [nameof(Program_PasswordRecoveryTokenForAccount)] = "Password recovery token for account {0}: {1}\n\n",
        [nameof(Program_TheTokenIsValidFor)] = "The token is valid for 30 minutes. Enter it in the client's \"Password recovery\" window and set a new password.\n",
        [nameof(Program_IfYouDidNotRequest)] = "If you did not request this, ignore this email.",
        [nameof(Program_RemoteAppClientPasswordRecoveryToken)] = "RemoteAppClient - password recovery token",
        [nameof(Program_AccessResultDeviceOutcomeNonce)] = "Access result {Device}: {Outcome} (nonce {Nonce})",
        [nameof(Program_AuditWriteAccessFailed)] = "Audit write (access) failed.",
        [nameof(SshRevocationList_UpdateFailed)] = "Could not put the SSH key of deleted device {Device} on the bastion's revocation list.",
        [nameof(SshRevocationList_BuildFailed)] = "Could not rebuild the bastion's SSH revocation list; the previous one stays in place: {Error}",
        [nameof(SshRevocationList_Rebuilt)] = "Bastion SSH revocation list {Path} rebuilt: {Count} revoked key(s).",
        [nameof(Program_AgentMessageTooLarge)] = "Device {Device} sent a message over {Max} bytes on its command channel; the connection was closed.",
        [nameof(Program_ProxyFingerprintMissing)] = "nginx sends the proxy secret but not X-Client-Fingerprint: device certificates are not compared with the one last issued. Shown once until the server restarts.",
        [nameof(Program_ProxyHeadersWithoutSecret)] = "Identity or address headers ignored on a request without the proxy secret (from {Ip}, {Path}). If agents are being turned away, nginx is not sending X-RAC-Proxy yet. Shown once until the server restarts.",
        [nameof(Program_UnparseableAgentMessageDevice)] = "Unparseable agent message {Device}.",
        [nameof(Program_EmailDidNotMatch)] = "email did not match",
        [nameof(Program_Error)] = "error: {0}",
        [nameof(Program_MintBlobFirstRunCheck)] = "=== RemoteServer first-run check ===",
        [nameof(Program_MintBlobDbReachableSchemaApplied)] = "DB reachable + schema applied",
        [nameof(Program_MintBlobRunSchemaAndCheckConnection)] = "run schema.sql and check the 'MariaDb' connection string",
        [nameof(Program_MintBlobAdminExists)] = "Admin user exists (temporary password in {0}, removed after the first change; first sign-in requires a change)",
        [nameof(Program_MintBlobCommandSigningKey)] = "Command-signing key (Server:CommandSigningKeyPath)",
        [nameof(Program_MintBlobCaCertAndKey)] = "CA cert + key (Server:CaCertPath / CaKeyPath)",
        [nameof(Program_MintBlobGenerateCaSeeFirstRun)] = "generate the CA (run deploy/setup.sh)",
        [nameof(Program_MintBlobEmpty)] = "empty",
        [nameof(Program_MintBlobSetServerPublicUrl)] = "set Server:PublicUrl",
        [nameof(Program_MintBlobBastionHostAndHostKey)] = "Bastion host + host key (required for the reverse tunnel, not for the blob itself)",
        [nameof(Program_MintBlobSecretKey)] = "Secret key (auto-generated if missing)",
        [nameof(Program_MintBlobMissingRequiredItems)] = "\n{0} required item(s) missing - fix them and run this again. No blob was created.",
        [nameof(Program_MintBlobHeader)] = "\n=== Bootstrap blob (autoApprove=false -> devices enter Pending and need manual approval) ===\n",
        [nameof(Program_MintBlobUsage)] = "\nUsage: on the agent, run RemoteAgent.exe bootstrap \"<blob>\"; the first MSI can embed this blob.",
        [nameof(Program_MintBlobGenerationError)] = "\nBlob generation error: {0}",
        [nameof(SecretExpiryWatcher_SecretExpiryCheckError)] = "Secret expiry check error.",
        [nameof(SecretExpiryWatcher_TheRemoteAppClientEmailDeliveryGraph)] = "The RemoteAppClient email delivery (Graph) client secret has EXPIRED ({0}). Update it in Server settings or email delivery will not work.",
        [nameof(SecretExpiryWatcher_TheRemoteAppClientEmailDeliveryGraph_2)] = "The RemoteAppClient email delivery (Graph) client secret expires in {0} days ({1}). Create a new one in Azure and update it in Server settings.",
        [nameof(SecretExpiryWatcher_RemoteAppClientEmailDeliverySecretExpires)] = "RemoteAppClient: email delivery secret expires soon",
        [nameof(SecretExpiryWatcher_SecretExpiryWarningSentTo)] = "Secret expiry warning sent: {To} ({Days} days).",
        [nameof(SecretExpiryWatcher_SecretExpiryWarningSendFailed)] = "Secret expiry warning send failed: {Error}",
        [nameof(SecretProtector_EncryptionKeyIsMissingGenerate)] = "Encryption key is missing ('{0}'). Generate it during server setup (deploy/setup.sh).",
        [nameof(SecretProtector_EncryptionKeyIsNot32)] = "Encryption key is not 32 bytes ({0}).",
        [nameof(SecretProtector_SecretEncryptionKeyLoaded)] = "Secret encryption key loaded.",
        [nameof(SshCertificateAuthority_SSHCAKeyNotFound)] = "SSH CA key not found: {Path}",
        [nameof(SshCertificateAuthority_SshKeygenSigningFailedDevice)] = "ssh-keygen signing failed (device {Device}): {Err}",
        [nameof(HealthAlert_CheckError)] = "The server health check failed.",
        [nameof(HealthAlert_Failing)] = "Health alert [{Key}]: {Text}",
        [nameof(HealthAlert_Cleared)] = "Health alert cleared [{Key}].",
        [nameof(HealthAlert_NoRecipient)] = "No SupportEmail is set; health alerts go to the log only.",
        [nameof(HealthAlert_Sent)] = "Alert e-mail sent: {To} ({Failing} failing, {Cleared} cleared).",
        [nameof(HealthAlert_SendFailed)] = "Alert e-mail could not be sent: {Err}",
        [nameof(HealthAlert_Subject)] = "RemoteAppClient server ({0}): {1} alert(s), {2} cleared",
        [nameof(HealthAlert_Intro)] = "Server: {0} · version {1} · {2} UTC",
        [nameof(HealthAlert_SectionNew)] = "NEW",
        [nameof(HealthAlert_SectionStill)] = "STILL FAILING",
        [nameof(HealthAlert_SectionCleared)] = "CLEARED",
        [nameof(HealthAlert_Footer)] = "Details: console → Server settings → Diagnostics, or racctl diag.",
        [nameof(HealthAlert_Disk)] = "Disk {0}: {1} GB free of {2} GB.",
        [nameof(HealthAlert_DbDown)] = "The database is unreachable: {0}",
        [nameof(HealthAlert_DbSlow)] = "The database is slow: {0} ms per query.",
        [nameof(HealthAlert_TlsFailed)] = "The public TLS check failed: {0}",
        [nameof(HealthAlert_TlsExpiring)] = "The TLS certificate expires in {0} days ({1}); certbot renewal has probably stopped.",
        [nameof(HealthAlert_PackagesMissing)] = "Package file(s) missing: {0}",
        [nameof(HealthAlert_LogDir)] = "The log directory is unusable: {0}",
        [nameof(HealthAlert_UpdateFailed)] = "The last server update failed ({0}); the helper rolled back to the previous version.",
        [nameof(HealthAlert_DeviceCerts)] = "{0} device certificate(s) expire within {1} days (first: {2} on {3}); {4} already expired. There is no renewal: these devices must be re-enrolled.",
        [nameof(HealthAlert_NoCommandChannel)] = "{0} device(s) send telemetry but none is on the command channel; the 443 mux or nginx's /agent route is probably stuck.",
    };
}
