using System.Collections.Generic;

namespace RemoteServer.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> Hu = new()
    {
        [nameof(CertificateAuthority_001)] = "A CA fájlok hiányoznak ('{0}', '{1}'). ",
        [nameof(CertificateAuthority_002)] = "Generáld provisioning-kor (deploy/deploy-server.sh), a szerver csak olvassa.",
        [nameof(CertificateAuthority_003)] = "CA betöltve: {Subject}",
        [nameof(CommandService_001)] = "Ismeretlen gép, parancs eldobva: {Device}",
        [nameof(CommandService_002)] = "Parancs kézbesítve {Device}: {Type}",
        [nameof(CommandService_003)] = "Gép offline, parancs sorban marad {Device}: {Type}",
        [nameof(CommandSigner_001)] = "A parancs-aláíró privát kulcs nem található: '{0}'. Állítsd be a Server:CommandSigningKeyPath-ot.",
        [nameof(EmailSender_001)] = "Hiányzó címzett.",
        [nameof(EmailSender_002)] = "Nincs e-mail beállítás.",
        [nameof(EmailSender_003)] = "Nincs aktív e-mail provider beállítva.",
        [nameof(EmailSender_004)] = "E-mail küldés hiba ({Provider}).",
        [nameof(EmailSender_005)] = "Hiányzó SMTP host.",
        [nameof(EmailSender_006)] = "Hiányzó feladó (SmtpFrom/SmtpUser).",
        [nameof(EmailSender_007)] = "Hiányzó Graph beállítás (tenant/client/sender).",
        [nameof(EmailSender_008)] = "Hiányzó Graph client secret.",
        [nameof(EmailSender_009)] = "A token-válasz nem tartalmaz access_token-t.",
        [nameof(EmailSender_010)] = "Token hiba ({0}): {1}",
        [nameof(EmailSender_011)] = "sendMail hiba ({0}): {1}",
        [nameof(EnrollmentService_001)] = "CSR aláírása sikertelen (device {Device}).",
        [nameof(EnrollmentService_002)] = "Gép beléptetve: {Device} ({Host})",
        [nameof(MsiBuilder_001)] = "MSI legyártva: {File} ({Size} bájt)",
        [nameof(MsiBuilder_002)] = "MSI gyártás hiba.",
        [nameof(MsiBuilder_003)] = "MSI aláírva.",
        [nameof(MsiBuilder_004)] = "MSI aláírás kihagyva/sikertelen (osslsigncode rc={Code}): {Output}",
        [nameof(MsiBuilder_005)] = "MSI aláírás hiba (kihagyva).",
        [nameof(MsiBuilder_006)] = "wixl hiba (rc={Code}): {Output}",
        [nameof(Program_001)] = "ismeretlen felhasználó",
        [nameof(Program_002)] = "hibás jelszó",
        [nameof(Program_003)] = "hibás TOTP",
        [nameof(Program_004)] = "ismeretlen gép",
        [nameof(Program_005)] = "érvénytelen vagy lejárt token",
        [nameof(Program_006)] = "WS lezárult: {Device}",
        [nameof(Program_007)] = "Agent lekapcsolódott: {Device}",
        [nameof(Program_008)] = "{0} · {1} · {2} → {3} gép",
        [nameof(Program_009)] = "állítsd be a Server:PublicUrl-t vagy add meg: ?serverUrl=",
        [nameof(Program_010)] = "; smtpPassword=változott",
        [nameof(Program_011)] = "; graphSecret=változott",
        [nameof(Program_012)] = "Ez egy teszt e-mail a RemoteAppClient szerver-beállításokból. Ha megkaptad, a küldés működik.",
        [nameof(Program_013)] = "BOOTSTRAP admin létrehozva — felhasználónév: admin, IDEIGLENES jelszó: {Temp} (első belépéskor cserélni kell)",
        [nameof(Program_014)] = "Audit írás hiba: {Action}",
        [nameof(Program_015)] = "{0} sikertelen próba (utolsó: {1})",
        [nameof(Program_016)] = "A(z) „{0}” gépről {1} sikertelen belépési/jelszó-próba történt — a gép BELÉPÉS-ZÁROLVA.\n\n",
        [nameof(Program_017)] = "Utolsó próbált felhasználónév: {0}\nForrás IP: {1}\nIdő: {2:yyyy-MM-dd HH:mm} UTC\n\n",
        [nameof(Program_018)] = "Feloldás: a kliensben Eszközök → a gép → „Belépés feloldása” (csak admin).",
        [nameof(Program_019)] = "RemoteAppClient – gép belépés-zárolva (sikertelen próbák)",
        [nameof(Program_020)] = "Jelszó-helyreállítási token a(z) {0} fiókhoz: {1}\n\n",
        [nameof(Program_021)] = "A token 30 percig érvényes. Írd be a kliens „Jelszó helyreállítás” ablakába, és állíts be új jelszót.\n",
        [nameof(Program_022)] = "Ha nem te kérted, hagyd figyelmen kívül ezt a levelet.",
        [nameof(Program_023)] = "RemoteAppClient – jelszó-helyreállítási token",
        [nameof(Program_024)] = "Hozzáférés-eredmény {Device}: {Outcome} (nonce {Nonce})",
        [nameof(Program_025)] = "Audit-írás (access) sikertelen.",
        [nameof(Program_026)] = "Értelmezhetetlen agent-üzenet {Device}.",
        [nameof(Program_027)] = "e-mail nem egyezett",
        [nameof(Program_028)] = "hiba: {0}",
        [nameof(SecretExpiryWatcher_001)] = "Secret-lejárat ellenőrzés hiba.",
        [nameof(SecretExpiryWatcher_002)] = "A RemoteAppClient levélküldési (Graph) client secret-je LEJÁRT ({0}). Frissítsd a Szerver beállításokban, különben nem megy az e-mail küldés.",
        [nameof(SecretExpiryWatcher_003)] = "A RemoteAppClient levélküldési (Graph) client secret-je {0} napon belül lejár ({1}). Hozz létre újat az Azure-ban, és frissítsd a Szerver beállításokban.",
        [nameof(SecretExpiryWatcher_004)] = "RemoteAppClient: a levélküldési secret hamarosan lejár",
        [nameof(SecretExpiryWatcher_005)] = "Secret-lejárat figyelmeztető elküldve: {To} ({Days} nap).",
        [nameof(SecretExpiryWatcher_006)] = "Secret-lejárat figyelmeztető küldése sikertelen: {Error}",
        [nameof(SecretProtector_001)] = "A titkosító kulcs hiányzik ('{0}'). Generáld provisioning-kor (deploy-server.sh).",
        [nameof(SecretProtector_002)] = "A titkosító kulcs nem 32 bájt ({0}).",
        [nameof(SecretProtector_003)] = "Titok-titkosító kulcs betöltve.",
        [nameof(SshCertificateAuthority_001)] = "SSH-CA kulcs nem található: {Path}",
        [nameof(SshCertificateAuthority_002)] = "ssh-keygen aláírás sikertelen (device {Device}): {Err}",
    };
}
