using System.Collections.Generic;

namespace RemoteServer.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> En = new()
    {
        [nameof(CertificateAuthority_001)] = "CA files are missing ('{0}', '{1}'). ",
        [nameof(CertificateAuthority_002)] = "Generate them during provisioning (deploy/deploy-server.sh); the server only reads them.",
        [nameof(CertificateAuthority_003)] = "CA loaded: {Subject}",
        [nameof(CommandService_001)] = "Unknown device, command discarded: {Device}",
        [nameof(CommandService_002)] = "Command delivered to {Device}: {Type}",
        [nameof(CommandService_003)] = "Device offline, command remains queued {Device}: {Type}",
        [nameof(CommandSigner_001)] = "Command signing private key not found: '{0}'. Set Server:CommandSigningKeyPath.",
        [nameof(EmailSender_001)] = "Missing recipient.",
        [nameof(EmailSender_002)] = "No email settings.",
        [nameof(EmailSender_003)] = "No active email provider configured.",
        [nameof(EmailSender_004)] = "E-mail delivery error ({Provider}).",
        [nameof(EmailSender_005)] = "Missing SMTP host.",
        [nameof(EmailSender_006)] = "Missing sender (SmtpFrom/SmtpUser).",
        [nameof(EmailSender_007)] = "Missing Graph settings (tenant/client/sender).",
        [nameof(EmailSender_008)] = "Missing Graph client secret.",
        [nameof(EmailSender_009)] = "Token response does not contain access_token.",
        [nameof(EmailSender_010)] = "Token error ({0}): {1}",
        [nameof(EmailSender_011)] = "sendMail error ({0}): {1}",
        [nameof(EnrollmentService_001)] = "CSR signing failed (device {Device}).",
        [nameof(EnrollmentService_002)] = "Device enrolled: {Device} ({Host})",
        [nameof(MsiBuilder_001)] = "MSI built: {File} ({Size} bytes)",
        [nameof(MsiBuilder_002)] = "MSI build error.",
        [nameof(MsiBuilder_003)] = "MSI signed.",
        [nameof(MsiBuilder_004)] = "MSI signing skipped/failed (osslsigncode rc={Code}): {Output}",
        [nameof(MsiBuilder_005)] = "MSI signing error (skipped).",
        [nameof(MsiBuilder_006)] = "wixl error (rc={Code}): {Output}",
        [nameof(Program_001)] = "unknown user",
        [nameof(Program_002)] = "invalid password",
        [nameof(Program_003)] = "invalid TOTP",
        [nameof(Program_004)] = "unknown device",
        [nameof(Program_005)] = "invalid or expired token",
        [nameof(Program_006)] = "WS closed: {Device}",
        [nameof(Program_007)] = "Agent disconnected: {Device}",
        [nameof(Program_008)] = "{0} · {1} · {2} -> {3} devices",
        [nameof(Program_009)] = "set Server:PublicUrl or provide ?serverUrl=",
        [nameof(Program_010)] = "; smtpPassword=changed",
        [nameof(Program_011)] = "; graphSecret=changed",
        [nameof(Program_012)] = "This is a test email from RemoteAppClient server settings. If you received it, email delivery works.",
        [nameof(Program_013)] = "BOOTSTRAP admin created - username: admin, TEMPORARY password: {Temp} (must be changed at first sign-in)",
        [nameof(Program_014)] = "Audit write error: {Action}",
        [nameof(Program_015)] = "{0} failed attempts (last: {1})",
        [nameof(Program_016)] = "There were {1} failed sign-in/password attempts from device \"{0}\\",
        [nameof(Program_017)] = "Last attempted username: {0}\nSource IP: {1}\nTime: {2:yyyy-MM-dd HH:mm} UTC\n\n",
        [nameof(Program_018)] = "Unlock: in the client, go to Devices -> the device -> \"Unlock sign-in\" (admin only).",
        [nameof(Program_019)] = "RemoteAppClient - device sign-in locked (failed attempts)",
        [nameof(Program_020)] = "Password recovery token for account {0}: {1}\n\n",
        [nameof(Program_021)] = "The token is valid for 30 minutes. Enter it in the client's \"Password recovery\" window and set a new password.\n",
        [nameof(Program_022)] = "If you did not request this, ignore this email.",
        [nameof(Program_023)] = "RemoteAppClient - password recovery token",
        [nameof(Program_024)] = "Access result {Device}: {Outcome} (nonce {Nonce})",
        [nameof(Program_025)] = "Audit write (access) failed.",
        [nameof(Program_026)] = "Unparseable agent message {Device}.",
        [nameof(Program_027)] = "email did not match",
        [nameof(Program_028)] = "error: {0}",
        [nameof(SecretExpiryWatcher_001)] = "Secret expiry check error.",
        [nameof(SecretExpiryWatcher_002)] = "The RemoteAppClient email delivery (Graph) client secret has EXPIRED ({0}). Update it in Server settings or email delivery will not work.",
        [nameof(SecretExpiryWatcher_003)] = "The RemoteAppClient email delivery (Graph) client secret expires in {0} days ({1}). Create a new one in Azure and update it in Server settings.",
        [nameof(SecretExpiryWatcher_004)] = "RemoteAppClient: email delivery secret expires soon",
        [nameof(SecretExpiryWatcher_005)] = "Secret expiry warning sent: {To} ({Days} days).",
        [nameof(SecretExpiryWatcher_006)] = "Secret expiry warning send failed: {Error}",
        [nameof(SecretProtector_001)] = "Encryption key is missing ('{0}'). Generate it during provisioning (deploy-server.sh).",
        [nameof(SecretProtector_002)] = "Encryption key is not 32 bytes ({0}).",
        [nameof(SecretProtector_003)] = "Secret encryption key loaded.",
        [nameof(SshCertificateAuthority_001)] = "SSH CA key not found: {Path}",
        [nameof(SshCertificateAuthority_002)] = "ssh-keygen signing failed (device {Device}): {Err}",
    };
}
