using System.Collections.Generic;

namespace RemoteServer.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> Hu = new()
    {
        [nameof(CertificateAuthority_CAFilesAreMissing)] = "A CA fájlok hiányoznak ('{0}', '{1}'). ",
        [nameof(CertificateAuthority_GenerateThemDuringProvisioningDeploy)] = "Generáld a szerver telepítésekor (deploy/setup.sh), a szerver csak olvassa.",
        [nameof(CertificateAuthority_CALoadedSubject)] = "CA betöltve: {Subject}",
        [nameof(CommandService_UnknownDeviceCommandDiscardedDevice)] = "Ismeretlen gép, parancs eldobva: {Device}",
        [nameof(CommandService_CommandDeliveredToDeviceType)] = "Parancs kézbesítve {Device}: {Type}",
        [nameof(CommandService_DeviceOfflineCommandRemainsQueued)] = "Gép offline, parancs sorban marad {Device}: {Type}",
        [nameof(CommandSigner_CommandSigningPrivateKeyNot)] = "A parancs-aláíró privát kulcs nem található: '{0}'. Állítsd be a Server:CommandSigningKeyPath-ot.",
        [nameof(EmailSender_MissingRecipient)] = "Hiányzó címzett.",
        [nameof(EmailSender_NoEmailSettings)] = "Nincs e-mail beállítás.",
        [nameof(EmailSender_NoActiveEmailProviderConfigured)] = "Nincs aktív e-mail provider beállítva.",
        [nameof(EmailSender_EMailDeliveryErrorProvider)] = "E-mail küldés hiba ({Provider}).",
        [nameof(EmailSender_MissingSMTPHost)] = "Hiányzó SMTP host.",
        [nameof(EmailSender_MissingSenderSmtpFromSmtpUser)] = "Hiányzó feladó (SmtpFrom/SmtpUser).",
        [nameof(EmailSender_MissingGraphSettingsTenantClient)] = "Hiányzó Graph beállítás (tenant/client/sender).",
        [nameof(EmailSender_MissingGraphClientSecret)] = "Hiányzó Graph client secret.",
        [nameof(EmailSender_TokenResponseDoesNotContain)] = "A token-válasz nem tartalmaz access_token-t.",
        [nameof(EmailSender_TokenError)] = "Token hiba ({0}): {1}",
        [nameof(EmailSender_SendMailError)] = "sendMail hiba ({0}): {1}",
        [nameof(EnrollmentService_CSRSigningFailedDeviceDevice)] = "CSR aláírása sikertelen (device {Device}).",
        [nameof(EnrollmentService_DeviceEnrolledDeviceHost)] = "Gép beléptetve: {Device} ({Host})",
        [nameof(MsiBuilder_MSIBuiltFileSizeBytes)] = "MSI legyártva: {File} ({Size} bájt)",
        [nameof(MsiBuilder_MSIBuildError)] = "MSI gyártás hiba.",
        [nameof(MsiBuilder_MSISigned)] = "MSI aláírva.",
        [nameof(MsiBuilder_MSISigningSkippedFailedOsslsigncode)] = "MSI aláírás kihagyva/sikertelen (osslsigncode rc={Code}): {Output}",
        [nameof(MsiBuilder_MSISigningErrorSkipped)] = "MSI aláírás hiba (kihagyva).",
        [nameof(MsiBuilder_WixlErrorRcCodeOutput)] = "wixl hiba (rc={Code}): {Output}",
        [nameof(Program_UnknownUser)] = "ismeretlen felhasználó",
        [nameof(Program_InvalidPassword)] = "hibás jelszó",
        [nameof(Program_InvalidTOTP)] = "hibás TOTP",
        [nameof(Program_UnknownDevice)] = "ismeretlen gép",
        [nameof(Program_InvalidOrExpiredToken)] = "érvénytelen vagy lejárt token",
        [nameof(Program_AgentConnectedDevice)] = "Agent csatlakozott: {Device}",
        [nameof(Program_WSClosedDevice)] = "WS lezárult: {Device}",
        [nameof(Program_AgentDisconnectedDevice)] = "Agent lekapcsolódott: {Device}",
        [nameof(Program_Devices)] = "{0} · {1} · {2} → {3} gép",
        [nameof(Program_SetServerPublicUrlOrProvide)] = "állítsd be a Server:PublicUrl-t vagy add meg: ?serverUrl=",
        [nameof(Program_SmtpPasswordChanged)] = "; smtpPassword=változott",
        [nameof(Program_GraphSecretChanged)] = "; graphSecret=változott",
        [nameof(Program_ThisIsATestEmail)] = "Ez egy teszt e-mail a RemoteAppClient szerver-beállításokból. Ha megkaptad, a küldés működik.",
        [nameof(Program_BOOTSTRAPAdminCreatedUsernameAdmin)] = "BOOTSTRAP admin létrehozva — felhasználónév: admin, IDEIGLENES jelszó: {Temp} (első belépéskor cserélni kell)",
        [nameof(Program_RekeyCsrFailed)] = "Kulcscsere: a(z) {Device} eszköz CSR-jét nem sikerült aláírni",
        [nameof(Program_RekeyIssued)] = "Kulcscsere: új tanúsítvány kiadva a(z) {Device} eszköznek ({Reason}, kulcs: {Provider}); megerősítésre vár",
        [nameof(Program_RekeyConfirmed)] = "Kulcscsere: a(z) {Device} eszköz megerősítette az új tanúsítványt; a régi néhány perc múlva lejár",
        [nameof(Program_BOOTSTRAPAdminCreatedPasswordFile)] = "BOOTSTRAP admin létrehozva — felhasználónév: admin, az IDEIGLENES jelszó itt: {Path} (első belépéskor cserélni kell)",
        [nameof(FirstAdminHandover_CouldNotWrite)] = "Nem sikerült kiírni az első admin jelszófájlját: {Path}",
        [nameof(FirstAdminHandover_CouldNotRemove)] = "Nem sikerült törölni az első admin jelszófájlját: {Path}",
        [nameof(Program_AuditWriteErrorAction)] = "Audit írás hiba: {Action}",
        [nameof(Program_FailedAttemptsLast)] = "{0} sikertelen próba (utolsó: {1})",
        [nameof(Program_ThereWereFailedSignIn)] = "A(z) „{0}” gépről {1} sikertelen belépési/jelszó-próba történt — a gép BELÉPÉS-ZÁROLVA.\n\n",
        [nameof(Program_LastAttemptedUsernameSourceIP)] = "Utolsó próbált felhasználónév: {0}\nForrás IP: {1}\nIdő: {2:yyyy-MM-dd HH:mm} UTC\n\n",
        [nameof(Program_UnlockInTheClientGo)] = "Feloldás: a kliensben Eszközök → a gép → „Belépés feloldása” (csak admin).",
        [nameof(Program_RemoteAppClientDeviceSignInLocked)] = "RemoteAppClient – gép belépés-zárolva (sikertelen próbák)",
        [nameof(Program_PasswordRecoveryTokenForAccount)] = "Jelszó-helyreállítási token a(z) {0} fiókhoz: {1}\n\n",
        [nameof(Program_TheTokenIsValidFor)] = "A token 30 percig érvényes. Írd be a kliens „Jelszó helyreállítás” ablakába, és állíts be új jelszót.\n",
        [nameof(Program_IfYouDidNotRequest)] = "Ha nem te kérted, hagyd figyelmen kívül ezt a levelet.",
        [nameof(Program_RemoteAppClientPasswordRecoveryToken)] = "RemoteAppClient – jelszó-helyreállítási token",
        [nameof(Program_AccessResultDeviceOutcomeNonce)] = "Hozzáférés-eredmény {Device}: {Outcome} (nonce {Nonce})",
        [nameof(Program_AuditWriteAccessFailed)] = "Audit-írás (access) sikertelen.",
        [nameof(SshRevocationList_UpdateFailed)] = "A törölt eszköz ({Device}) SSH-kulcsát nem sikerült felvenni a bastion visszavonási listájára.",
        [nameof(SshRevocationList_BuildFailed)] = "A bastion SSH-visszavonási listáját nem sikerült újragenerálni, az előző marad érvényben: {Error}",
        [nameof(SshRevocationList_Rebuilt)] = "A bastion SSH-visszavonási listája ({Path}) újragenerálva: {Count} visszavont kulcs.",
        [nameof(Program_AgentMessageTooLarge)] = "A(z) {Device} eszköz {Max} bájtnál nagyobb üzenetet küldött a parancscsatornán; a kapcsolat bontva.",
        [nameof(Program_ProxyFingerprintMissing)] = "Az nginx küldi a proxy-titkot, de az X-Client-Fingerprint fejlécet nem: az eszköz-tanúsítványok nincsenek összevetve a legutóbb kiadottal. Újraindításig csak egyszer jelenik meg.",
        [nameof(Program_ProxyHeadersWithoutSecret)] = "Azonossági vagy cím-fejlécek figyelmen kívül hagyva egy proxy-titok nélküli kérésen ({Ip}, {Path}). Ha az agenteket elutasítja a szerver, az nginx még nem küldi az X-RAC-Proxy fejlécet. Újraindításig csak egyszer jelenik meg.",
        [nameof(Program_UnparseableAgentMessageDevice)] = "Értelmezhetetlen agent-üzenet {Device}.",
        [nameof(Program_EmailDidNotMatch)] = "e-mail nem egyezett",
        [nameof(Program_Error)] = "hiba: {0}",
        [nameof(Program_MintBlobFirstRunCheck)] = "=== RemoteServer első indítás ellenőrzése ===",
        [nameof(Program_MintBlobDbReachableSchemaApplied)] = "DB elérhető + séma betöltve",
        [nameof(Program_MintBlobRunSchemaAndCheckConnection)] = "futtasd a schema.sql-t, és ellenőrizd a 'MariaDb' connection stringet",
        [nameof(Program_MintBlobAdminExists)] = "Admin felhasználó létezik (ideiglenes jelszó itt: {0}, az első csere után törlődik; első belépéskor csere kell)",
        [nameof(Program_MintBlobCommandSigningKey)] = "Parancs-aláíró kulcs (Server:CommandSigningKeyPath)",
        [nameof(Program_MintBlobCaCertAndKey)] = "CA cert + kulcs (Server:CaCertPath / CaKeyPath)",
        [nameof(Program_MintBlobGenerateCaSeeFirstRun)] = "generáld a CA-t (futtasd: deploy/setup.sh)",
        [nameof(Program_MintBlobEmpty)] = "üres",
        [nameof(Program_MintBlobSetServerPublicUrl)] = "állítsd be a Server:PublicUrl-t",
        [nameof(Program_MintBlobBastionHostAndHostKey)] = "Bastion host + host kulcs (a reverse tunnelhez kell, magához a blobhoz nem)",
        [nameof(Program_MintBlobSecretKey)] = "Secret kulcs (automatikusan generált, ha hiányzik)",
        [nameof(Program_MintBlobMissingRequiredItems)] = "\n{0} kötelező elem hiányzik - pótold, majd futtasd újra. Blob nem készült.",
        [nameof(Program_MintBlobHeader)] = "\n=== Bootstrap blob (autoApprove=false -> a gépek Pending állapotba kerülnek, kézi jóváhagyás kell) ===\n",
        [nameof(Program_MintBlobUsage)] = "\nHasználat: az agenten futtasd: RemoteAgent.exe bootstrap \"<blob>\"; az első MSI beágyazhatja ezt a blobot.",
        [nameof(Program_MintBlobGenerationError)] = "\nBlob generálási hiba: {0}",
        [nameof(SecretExpiryWatcher_SecretExpiryCheckError)] = "Secret-lejárat ellenőrzés hiba.",
        [nameof(SecretExpiryWatcher_TheRemoteAppClientEmailDeliveryGraph)] = "A RemoteAppClient levélküldési (Graph) client secret-je LEJÁRT ({0}). Frissítsd a Szerver beállításokban, különben nem megy az e-mail küldés.",
        [nameof(SecretExpiryWatcher_TheRemoteAppClientEmailDeliveryGraph_2)] = "A RemoteAppClient levélküldési (Graph) client secret-je {0} napon belül lejár ({1}). Hozz létre újat az Azure-ban, és frissítsd a Szerver beállításokban.",
        [nameof(SecretExpiryWatcher_RemoteAppClientEmailDeliverySecretExpires)] = "RemoteAppClient: a levélküldési secret hamarosan lejár",
        [nameof(SecretExpiryWatcher_SecretExpiryWarningSentTo)] = "Secret-lejárat figyelmeztető elküldve: {To} ({Days} nap).",
        [nameof(SecretExpiryWatcher_SecretExpiryWarningSendFailed)] = "Secret-lejárat figyelmeztető küldése sikertelen: {Error}",
        [nameof(SecretProtector_EncryptionKeyIsMissingGenerate)] = "A titkosító kulcs hiányzik ('{0}'). Generáld a szerver telepítésekor (deploy/setup.sh).",
        [nameof(SecretProtector_EncryptionKeyIsNot32)] = "A titkosító kulcs nem 32 bájt ({0}).",
        [nameof(SecretProtector_SecretEncryptionKeyLoaded)] = "Titok-titkosító kulcs betöltve.",
        [nameof(SshCertificateAuthority_SSHCAKeyNotFound)] = "SSH-CA kulcs nem található: {Path}",
        [nameof(SshCertificateAuthority_SshKeygenSigningFailedDevice)] = "ssh-keygen aláírás sikertelen (device {Device}): {Err}",
        [nameof(HealthAlert_CheckError)] = "A szerver egészség-ellenőrzése hibát dobott.",
        [nameof(HealthAlert_Failing)] = "Egészség-riasztás [{Key}]: {Text}",
        [nameof(HealthAlert_Cleared)] = "Egészség-riasztás megszűnt [{Key}].",
        [nameof(HealthAlert_NoRecipient)] = "Nincs SupportEmail beállítva; az egészség-riasztások csak a naplóba kerülnek.",
        [nameof(HealthAlert_Sent)] = "Riasztó e-mail elküldve: {To} ({Failing} hibás, {Cleared} megszűnt).",
        [nameof(HealthAlert_SendFailed)] = "A riasztó e-mail küldése sikertelen: {Err}",
        [nameof(HealthAlert_Subject)] = "RemoteAppClient szerver ({0}): {1} riasztás, {2} megszűnt",
        [nameof(HealthAlert_Intro)] = "Szerver: {0} · verzió {1} · {2} UTC",
        [nameof(HealthAlert_SectionNew)] = "ÚJ HIBA",
        [nameof(HealthAlert_SectionStill)] = "TOVÁBBRA IS HIBÁS",
        [nameof(HealthAlert_SectionCleared)] = "MEGSZŰNT",
        [nameof(HealthAlert_Footer)] = "Részletek: konzol → Szerver-beállítások → Diagnosztika, vagy racctl diag.",
        [nameof(HealthAlert_Disk)] = "Lemez {0}: {1} GB szabad a(z) {2} GB-ból.",
        [nameof(HealthAlert_DbDown)] = "Az adatbázis nem érhető el: {0}",
        [nameof(HealthAlert_DbSlow)] = "Az adatbázis lassú: {0} ms egy lekérdezés.",
        [nameof(HealthAlert_TlsFailed)] = "A nyilvános TLS-ellenőrzés sikertelen: {0}",
        [nameof(HealthAlert_TlsExpiring)] = "A TLS-tanúsítvány {0} nap múlva lejár ({1}); a certbot-megújítás valószínűleg elakadt.",
        [nameof(HealthAlert_PackagesMissing)] = "Hiányzó csomagfájl(ok): {0}",
        [nameof(HealthAlert_LogDir)] = "A naplómappa nem használható: {0}",
        [nameof(HealthAlert_UpdateFailed)] = "A legutóbbi szerverfrissítés elbukott ({0}); a helper visszaállt az előző verzióra.",
        [nameof(HealthAlert_DeviceCerts)] = "{0} eszköz tanúsítványa lejár {1} napon belül (első: {2}, {3}); {4} már lejárt. Megújítás nincs: ezeket újra be kell léptetni.",
        [nameof(HealthAlert_NoCommandChannel)] = "{0} eszköz küld telemetriát, de egy sincs a parancscsatornán; valószínűleg a 443-as mux vagy az nginx /agent útvonala akadt el.",
    };
}
